Added MesaGL library to Linux build for rvio_sw
AcademySoftwareFoundation/OpenRV pull request #168
Opened 2023-06-06 14:56 UTC by ThomBern

### Linked issues

### Summarize your change.
Added some new packages that install MesaGL libraries on the Linux build for the rvio_sw binary.
### Describe the reason for the change.
In case any linux machine does not have a GPU, in which case the rvio binary would not work. This is where rvio_sw comes in to save the day.
### Describe what you have tested and on which operating system.
Apparently would only be needed on Redhat distros, so the new binary and libraries only get installed on those distros (Rocky, Centos, etc.)
### Add a list of changes, and note any that might need special attention during the review.
New rvio_sw folder in imgtools
New CMake build libraries used in the rvio_sw binary:
- TwkGLFMesa
- MovieRV
Brought back the use of the RVIO_HW macro in rvio/main.cpp (from shotgun-rv)
### If possible, provide screenshots.

2023-06-06 15:10 UTC, geffrak requested changes

2023-06-06 15:10 UTC, geffrak commented on src/bin/imgtools/rvio/main.cpp
> +#include "UICommands.h"
It should be <UICommands.h>. It it doesn't work, fix your CMake Include path in rvio_sw

```
TARGET_INCLUDE_DIRECTORIES(
  ${_target}
  PRIVATE <path_to_rvio_hw>
)
```

2023-06-06 15:10 UTC, geffrak commented on src/bin/imgtools/rvio/UICommands.cpp
> +#include "UICommands.h"
It should be <UICommands.h>. It it doesn't work, fix your CMake Include path in rvio_sw

```
TARGET_INCLUDE_DIRECTORIES(
  ${_target}
  PRIVATE <path_to_rvio_hw>
)
```

2023-06-06 15:10 UTC, geffrak commented on src/lib/graphics/TwkGLFMesa/CMakeLists.txt
> +  PRIVATE TwkFB
TwkFB is public because it's in the .h

PUBLIC means that it's used in a header
PRIVATE means that it's used in a .cpp

2023-06-06 15:10 UTC, geffrak commented on src/bin/imgtools/rvio_sw/CMakeLists.txt
> +    "rvio_sw"
this one should be rvio and the other one rvio_hw, if we want to be on par with RV Commercial

2023-06-06 15:31 UTC, ThomBern commented on cmake/macros/FindOSMesa.cmake
> +# Try to find Mesa off-screen library and include dir. Once done this will define
This .cmake file was added by Bernie

2023-06-06 15:33 UTC, ThomBern commented on src/lib/image/MovieRV/CMakeLists.txt
> +TARGET_LINK_LIBRARIES(
TwkAudio isn't added in MovieRV, but it is in the rvio_sw CMakeLists; should I change that one to PUBLIC?

2023-06-06 15:49 UTC, ThomBern commented on src/bin/imgtools/rvio_sw/CMakeLists.txt
> +    "rvio_sw"
I should also change the folder names right? Would that cause any problem in the builds?

2023-06-06 15:50 UTC, geffrak commented on src/bin/imgtools/rvio_sw/CMakeLists.txt
> +    "rvio_sw"
Yes for both and the .wrapper file name and content

2023-06-06 16:07 UTC, ThomBern commented on src/lib/image/MovieRV/CMakeLists.txt
> +TARGET_LINK_LIBRARIES(
what happens if a library is used in both, for example, the MuTwkApp/MuInterface is used in UCommands.h and main.cpp (rvio_hw)

2023-06-06 16:31 UTC, geffrak commented on cmake/macros/FindOSMesa.cmake
> +# Try to find Mesa off-screen library and include dir. Once done this will define
@bernie-laberge, do you know the licensing of that file?

2023-06-06 20:50 UTC, geffrak approved these changes

2023-06-06 20:50 UTC, geffrak commented on src/bin/imgtools/rvio/main.cpp
> +#ifdef RVIO_HW
Are we ever setting RVIO_HW?

2023-06-06 20:54 UTC, ThomBern commented on src/bin/imgtools/rvio/main.cpp
> +#ifdef RVIO_HW
But it's not there in the rvio_sw CMakeLists, since it's not needed.

2023-06-07 16:54 UTC, bernie-laberge commented on src/bin/imgtools/rvio_sw/glfix.c
> +#include <stdlib.h>
Please add the following header (Sorry I completely forgot ! My bad)
//
// Copyright (C) 2023  Autodesk, Inc. All Rights Reserved. 
// 
// SPDX-License-Identifier: Apache-2.0 
//

2023-06-07 16:54 UTC, bernie-laberge commented on src/lib/graphics/TwkGLFMesa/OSMesaVideoDevice.cpp
> +// All rights reserved.
Please add the // SPDX-License-Identifier: Apache-2.0:
//******************************************************************************
// Copyright (c) 2007 Tweak Inc. 
// All rights reserved.
// 
// SPDX-License-Identifier: Apache-2.0
// 
//******************************************************************************

2023-06-07 16:54 UTC, bernie-laberge commented on src/lib/graphics/TwkGLFMesa/TwkGLFMesa/OSMesaVideoDevice.h
> +// All rights reserved.
Please add the // SPDX-License-Identifier: Apache-2.0:
//******************************************************************************
// Copyright (c) 2007 Tweak Inc. 
// All rights reserved.
// 
// SPDX-License-Identifier: Apache-2.0
// 
//******************************************************************************

2023-06-07 16:54 UTC, bernie-laberge commented on src/lib/image/MovieRV/MovieRV.cpp
> +// Copyright (c) 2007 Tweak Inc.
We need to add the // SPDX-License-Identifier: Apache-2.0:
//******************************************************************************
// Copyright (c) 2007 Tweak Inc. 
// All rights reserved.
// 
// SPDX-License-Identifier: Apache-2.0
// 
//******************************************************************************

2023-06-07 16:54 UTC, bernie-laberge commented on src/lib/image/MovieRV/MovieRV/MovieRV.h
> +// All rights reserved.
We need to add the // SPDX-License-Identifier: Apache-2.0:
//******************************************************************************
// Copyright (c) 2007 Tweak Inc. 
// All rights reserved.
// 
// SPDX-License-Identifier: Apache-2.0
// 
//******************************************************************************

2023-07-07 16:42 UTC, geffrak approved these changes

2023-07-14 19:43 UTC, merged