Add a file logger system (with rotation and asynchronicity)
AcademySoftwareFoundation/OpenRV pull request #176
Opened 2023-06-13 13:44 UTC by ThomBern

### Linked issues

### Summarize your change.
This PR adds a new library, spdlog, which we will be  using for file logging.
A new library means a new dependence, and so there's a spdlog.cmake file that automatically fetches and builds the library, cool stuff.

### Describe the reason for the change.
This PR is a solution to a ticket, so users can share logs easily with support.
 
### Describe what you have tested and on which operating system.
As of June 13th, only on Mac! But it does build on Rocky 9.
### Add a list of changes, and note any that might need special attention during the review.
- spldlog.cmake
- The file logging happens in RvConsoleWindow. 
### If possible, provide screenshots.

2023-06-13 14:14 UTC, geffrak reviewed
Great way to add a file logger to OpenRV

2023-06-13 14:14 UTC, geffrak commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +    line[strcspn(line.c_str(), "\n")] = 0; // testing; to delete the newline char before the file logging
comment says to delete

2023-06-13 14:17 UTC, geffrak commented
What does the log file looks like? Does it have a timestamp? Does it tell when a new application session has started?

2023-06-13 17:49 UTC, ThomBern commented on src/lib/image/MovieFFMpeg/CMakeLists.txt
> +          RvCommon
Forgot to remove from an older implementation; removed

2023-06-13 17:50 UTC, ThomBern commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +    line[strcspn(line.c_str(), "\n")] = 0; // testing; to delete the newline char before the file logging
I use that line to remove the unnecessary newline which would 'double space' the log file.

2023-06-13 17:52 UTC, geffrak commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +    line[strcspn(line.c_str(), "\n")] = 0; // testing; to delete the newline char before the file logging
Can it be multiple \n in the message? I believe we support multiline logging. Also, if it's final, adjust your comment.

2023-06-13 18:11 UTC, ThomBern commented on src/lib/app/RvCommon/CMakeLists.txt
> +# QT Message Handler log levels (do we want to implement it, or not needed?)
So if we split the file and console log levels, I'm guessing we'd have 2 env vars, correct?

2023-06-13 18:17 UTC, ThomBern commented on src/lib/app/RvCommon/CMakeLists.txt
> +# QT Message Handler log levels (do we want to implement it, or not needed?)
Oh, and also, these QT options aren't used for the logger anymore, but I did try to log through the Qt message handler when starting this ticket. Although it's not used for the file logging, some messages still go through the Qt message handler, so the qt log output macros could still be useful.

2023-06-13 18:21 UTC, ThomBern commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +        m_fileLogger = spdlog::rotating_logger_mt<spdlog::async_factory>("RV_APP", "logs/rv_log.txt", 1024*1024*5, 2).get();
While we're at it, do we want to have be able to configure the log file size and the number of files in rotation?

2023-06-13 20:36 UTC, geffrak commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +    line[strcspn(line.c_str(), "\n")] = 0; // testing; to delete the newline char before the file logging
If you need this, use boost::trim_right or something similar

2023-06-14 17:15 UTC, bernie-laberge commented on src/lib/app/RvCommon/CMakeLists.txt
> +         spdlog::spdlog
Does it have to be public ? I would list spdlog in the PRIVATE section if it builds OK.

2023-06-14 17:30 UTC, bernie-laberge commented on src/lib/app/RvCommon/RvApplication.cpp
> +    Q_INIT_RESOURCE(RvCommon);
Extra space at the end. Please remove.

2023-06-14 17:36 UTC, bernie-laberge commented on src/lib/app/RvCommon/RvCommon/RvConsoleWindow.h
> +#include <spdlog/spdlog.h>
It is good practice when adding include files to first list the higher lever headers first (like RVApp/Options.h for example) and then other packages we might have added (Like Qt headers or spdlog headers) and then list last the c++ standard headers (like <<sstream>) 
If we were in Flame, we would be super strict about this but I propose we start introducing it in RV one commit at a time.

2023-06-14 17:36 UTC, bernie-laberge commented on src/lib/app/RvCommon/RvCommon/RvConsoleWindow.h
> +#include <spdlog/spdlog.h>
So the correct order would be:
#include <RvApp/Options.h>
#include <spdlog/spdlog.h>
#include <sstream>

2023-06-14 17:38 UTC, bernie-laberge commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +#include <spdlog/async.h>
[Please see my comment above about the include order]
Based on my previous comment, the correct order would be:
#include <RvCommon/QTUtils.h>
#include <RvCommon/RvConsoleWindow.h>
#include <RvPackage/PackageManager.h>
#include <TwkUtil/EnvVar.h>
#include <spdlog/async.h>
#include <spdlog/sinks/rotating_file_sink.h>
#include <iostream>
#include <string.h>
#include <stl_ext/string_algo.h>

2023-06-14 18:06 UTC, geffrak commented on .gitignore
> +logs/
No needs if the logs are stored at the right place.

2023-06-14 18:06 UTC, geffrak commented on src/lib/app/RvCommon/CMakeLists.txt
> +         spdlog::spdlog
It's being imported in the .h. It could be forward declared, however, since we just use the symbol to define a pointer.

2023-06-14 18:06 UTC, geffrak commented on src/lib/app/RvCommon/RvApplication.cpp
> +    Q_INIT_RESOURCE(RvCommon);
@bernie-laberge Should we introduce clang-format as a pre-commit hook, without running it on all the code base for now, just for cases like this in subsequent review?

2023-06-14 18:06 UTC, geffrak commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +        string logFileName = "/rv_log";
Please have the application name in the log file name

2023-06-14 18:06 UTC, geffrak commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +    if (line.find("ERROR:") == 0) lineLogLevel = spdlog::level::err;
I don't understand why we need to parse the lines. And what do you do if they are outside the lines?

2023-06-14 18:06 UTC, geffrak commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +    if (line.find("ERROR:") == 0) lineLogLevel = spdlog::level::err;
I don't understand why we need to parse the lines twice.

2023-06-14 18:06 UTC, geffrak commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +            case 1: m_fileLogger->debug(line); break;
Can you replace the numbers with the actual symbols?

2023-06-14 19:14 UTC, bernie-laberge commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +        string logFileName = "/rv_log";
I was discussing this with Kerby at the cafeteria and we think it would be nice to put all the FileLogger business logic in its own file.
src/lib/base/TwkUtil/FileLogger.h/.cpp
This way it could eventually be reused elsewhere (like rvio for example).

2023-06-14 19:17 UTC, bernie-laberge commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +    if(lineLogLevel < m_logLevel) return false;
I was discussing this with Kerby at the cafeteria and we think that we should remove this level for now and re-introduce it later if we need it (perhaps when Kerby or Shannon adds the python log support for it).
So let's keep it simple for now and complexify it on a per need basis.

2023-06-14 19:18 UTC, bernie-laberge commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +    if(lineLogLevel < m_logLevel) return false;
Wait : do we already know it is an error, warning, debug, info ?
Why do we need to parse the string ?

2023-06-14 19:26 UTC, geffrak commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +        m_fileLogger = spdlog::rotating_logger_mt<spdlog::async_factory>("RV_APP", "logs/rv_log.txt", 1024*1024*5, 2).get();
With environment variables, it's a good idea.

2023-06-14 19:31 UTC, bernie-laberge commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +    if (line.find("WARNING:") == 0) lineLogLevel = spdlog::level::warn;
Re-doing the same string comparisons is not optimal (See lines 326-329). 
Even the original code is sub-optimal : these levels are mutually exclusive so once we have detected one, the others do not have to be string compared.

2023-06-14 19:33 UTC, bernie-laberge commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +    if(lineLogLevel < m_logLevel) return false;
As an additional note: m_logLevel = envVar(RV_FILE_LOG_VERBOSITY_LEVEL)
The FILE LOG level. Not the regular console level.

2023-06-14 19:35 UTC, bernie-laberge commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +    if(lineLogLevel < m_logLevel) return false;
I was discussing this with Kerby at the cafeteria and we think that we should remove this RV_FILE_LOG_VERBOSITY_LEVEL level for now and re-introduce it later if we need it (perhaps when Kerby or Shannon adds the python log support for it).
So let's keep it simple for now and add complexity to it later if the really need it.

2023-06-14 19:37 UTC, bernie-laberge commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +    line[strcspn(line.c_str(), "\n")] = 0;
We should hide this business logic in the new FileLogger.cpp

2023-06-14 19:58 UTC, ThomBern commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +    if (line.find("ERROR:") == 0) lineLogLevel = spdlog::level::err;
The parsing was already something that was in that method, I just moved it around.

2023-06-14 20:40 UTC, ThomBern commented on src/lib/app/RvCommon/CMakeLists.txt
> +         spdlog::spdlog
m_fileLogger is of type spdlog::logger and is declared in the header, so until we create that new FileLogging.cpp file, I'll keep the spdlog lib in PUBLIC.

2023-06-16 15:36 UTC, geffrak commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +    m_fileLogger.logToFile(lineLogLevel, line);
Why aren't you hooked to the qtMessageHandler? It does all the work of finding the level, and it's a centralized place. I might be missing something.

2023-06-16 16:42 UTC, ThomBern commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +    m_fileLogger.logToFile(lineLogLevel, line);
From what I understand, to make the handler work, we'd need to call qDebug(), qInfo(), etc, everywhere we want to log something, and right now, nothing is using the qt message handler. RvConsoleWindow is also in RvApplication, and I believe it overloads the cout operator (what Bernie told me).

2023-06-16 16:54 UTC, bernie-laberge commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +#include <TwkUtil/EnvVar.h>
I think you can remove #include <TwkUtil/EnvVar.h> and #include <spdlog/common.h> as they are no longer necessary.

2023-06-16 16:59 UTC, bernie-laberge commented on src/lib/base/TwkUtil/FileLogger.cpp
> +        m_level = spdlog::level::debug;
missing indentation

2023-06-16 18:08 UTC, ThomBern commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +#include <TwkUtil/EnvVar.h>
I'm using the spdlog::level::level_enum enumeration for the line log values, and then passing that value to the logger.

2023-06-19 20:22 UTC, bernie-laberge approved these changes

2023-06-19 20:26 UTC, geffrak commented on src/lib/base/TwkUtil/FileLogger.cpp
> +        std::string logFilePath = (QDir::homePath().toStdString() + "/Library/Logs/");
/Library/Logs/ + QCoreApplication::organizationName()

2023-06-19 20:26 UTC, geffrak approved these changes

2023-06-19 20:32 UTC, ThomBern commented on src/lib/base/TwkUtil/FileLogger.cpp
> +        std::string logFilePath = (QDir::homePath().toStdString() + "/Library/Logs/");
For every OS?

2023-06-19 20:33 UTC, geffrak commented on src/lib/base/TwkUtil/FileLogger.cpp
> +        std::string logFilePath = (QDir::homePath().toStdString() + "/Library/Logs/");
No, just on MacOS.

2023-06-21 15:00 UTC, geffrak requested changes

2023-06-21 15:00 UTC, geffrak commented on src/lib/base/TwkUtil/FileLogger.cpp
> +        : m_loggerName(QCoreApplication::applicationName().toStdString())
: m_loggerName(QCoreApplication::applicationName().toStdString() + ".log")

2023-07-06 20:21 UTC, bernie-laberge commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +    spdlog::level::level_enum lineLogLevel;
You should initialize lineLogLevel to spdlog::level::info.
Otherwise it could potentially be uninitialized/random.

2023-07-06 20:21 UTC, bernie-laberge commented on src/lib/app/RvCommon/RvConsoleWindow.cpp
> +    spdlog::level::level_enum lineLogLevel;
You should initialize lineLogLevel to spdlog::level::info.
Otherwise it could potentially be uninitialized/random.

2023-07-06 20:23 UTC, geffrak approved these changes

2023-08-03 20:49 UTC, merged