Build RV using a Python virtual environment
AcademySoftwareFoundation/OpenRV pull request #514
Opened 2024-07-15 13:22 UTC by chxmberland

### Linked issues

N/A

### Summarize your change.

The Python version included with MacOS Sonoma 14.5 adopted [PEP 668](https://peps.python.org/pep-0668/), which is meant to prevent conflicts between system level Python packages with project specific Python packages, like what is included in `requirements.txt`. 

This means that the user will encounter an error when attempting to install Python requirements unless they use the tag `--break-system-packages` tag. By using a virtual environment, system-level conflicts are avoided and the user has a safer build of Open RV. 

### Describe what you have tested and on which operating system.

Mac OS Sonoma 14.5 and Windows 11.

### If possible, provide screenshots.

PEP 668 error without a virtual environment, triggered by running `rvbuild`.

![image](https://github.com/user-attachments/assets/c164a106-dff8-49f7-b2b9-690f46fc280e)

2024-07-15 13:26 UTC, geffrak requested changes
Please don't name it pyenv. Pyenv is a different thing and might confuse people (I got confused at first).

venv (or .venv) is is fine.

Also, can you run rvenv multiple times without errors?

2024-07-15 13:35 UTC, geffrak commented on rvcmds.sh
> +alias rvenv="python3.12 -m venv _virtualenv && source _virtualenv/bin/activate"
You can rename this for `python3 ...`

2024-07-18 19:25 UTC, bernie-laberge approved these changes

2024-07-18 19:27 UTC, geffrak approved these changes

2024-07-31 19:11 UTC, eloisebrosseau commented
Would you mind adding your changes to the README so that it reflects the contents of rvcmds.sh?

2024-08-06 13:24 UTC, bernie-laberge commented on README.md
> +See the **Using a Python Virtual Environment** before running any of the commands in this section. Python packages should be installed inside of a virtual environment.
I stumbled on that yesterday while setuping the new build agents: we should also add this note here I think: https://github.com/AcademySoftwareFoundation/OpenRV/blob/main/docs/build_system/config_macos.md#install-the-python-requirements

2024-08-12 19:43 UTC, closed without merging