Create Python virtual environment when Open RV/RV is being built
AcademySoftwareFoundation/OpenRV pull request #536
Opened 2024-08-12 19:44 UTC by chxmberland

### Linked issues

N/A

### Summarize your change.

The Python version included with MacOS Sonoma 14.5 adopted [PEP 668](https://peps.python.org/pep-0668/), which is meant to prevent conflicts between system level Python packages with project specific Python packages, like what is included in `requirements.txt`. 

This means that the user will encounter an error when attempting to install Python requirements unless they use the tag `--break-system-packages` tag. By using a virtual environment, system-level conflicts are avoided and the user has a safer build of Open RV. 

### Describe what you have tested and on which operating system.

Mac OS Sonoma 14.5 and Windows 11.

### If possible, provide screenshots.

PEP 668 error without a virtual environment, triggered by running `rvbuild`.

![image](https://github.com/user-attachments/assets/c164a106-dff8-49f7-b2b9-690f46fc280e)

2024-08-20 20:20 UTC, eloisebrosseau requested changes

2024-08-20 20:20 UTC, eloisebrosseau commented on rvcmds.sh
> +alias rvenv="[ -d "_virtualenv" ] && source _virtualenv/bin/activate || (python3 -m venv _virtualenv && source _virtualenv/bin/activate)"
The rvenv command does not activate the virtual environment the first time it is run. Have you try to use a function instead like so:
```rvenv() {
if [ -d ".venv" ]; then
    source .venv/bin/activate
else
    python3 -m venv .venv
    source .venv/bin/activate
fi
}
```

Removing the rvenv alias and doing it this way instead fixed the issue for me

2024-08-21 12:53 UTC, cedrik-fuoco-adsk commented on .gitignore
> +_virtualenv/*
`venv` is the module name, but you can name the folder however you want. In the link, they have an example with a custom name : `python -m venv tutorial-env`

2024-08-21 17:49 UTC, chxmberland commented on rvcmds.sh
> +alias rvenv="[ -d "_virtualenv" ] && source _virtualenv/bin/activate || (python3 -m venv _virtualenv && source _virtualenv/bin/activate)"
Ah I see, it's activating in a sub shell, that's why it's not working. Thank you!

2024-08-23 13:00 UTC, cedrik-fuoco-adsk commented on rvcmds.sh
> +alias rvclean="rm -rf ${RV_BUILD} && rm -rf _virtualenv"
Should change `_virtualenv` to the new name

2024-08-23 13:01 UTC, cedrik-fuoco-adsk commented on README.md
> +Open RV automatically sets up a Python virtual environment when the user bootstraps (`rvbootstrap`), builds (`rvbuild`) or configures (`rvcfg`) their project. After each of these commands, you should
Should change `_virtualenv` to the new name

2024-08-23 13:04 UTC, cedrik-fuoco-adsk commented on rvcmds.sh
> +    source .venv/bin/activate
The command should be `python3 -m venv .venv` if you want to create a `.venv` folder.

2024-08-23 13:41 UTC, eloisebrosseau commented on .gitignore
> +_venv/*
This should be changed to `.venv`

2024-08-23 13:45 UTC, cedrik-fuoco-adsk approved these changes

2024-08-23 13:53 UTC, chxmberland commented on docs/build_system/config_macos.md
>  ```bash
Good catch! Fixed

2024-08-23 14:58 UTC, eloisebrosseau approved these changes

2024-09-05 17:52 UTC, merged